#!/usr/bin/env bash
# Display information about subdomains.

digger () {
	# perform DNS lookup
	record=$(dig "$2.$1" | grep -A1 "ANSWER SECTION:" | tr "\t" "\n" | tail -2 | tr "\n" " ")
	echo "$2 $record" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ] 
then
	digger "$1" "www"
	digger "$1" "lb-01"
	digger "$1" "web-01"
	digger "$1" "web-02"
elif [ "$#" == 2 ]
then
	digger "$1" "$2"
fi
