#!/usr/bin/env bash
# installs nginx with the configuration
#+ Listen on port 80.
#+ Returns page containing "Hello World!"
#++ at root with a curl GET request

apt-get update
apt-get install nginx -y

mkdir /var/www/html
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
printf %s "server {
	listen    80 default_server;
	listen    [::]:80 default_server;
	root      /var/www/html;
	index     index.html index.htm index.nginx-debian.html;
}
" > /etc/nginx/sites-available/default

service nginx restart
