#!/usr/bin/env bash
# Installs Nginx with the following configurations
# Listen on port 80
# return a page containing "Hello World!" with a curl GET request.
# Configure an Nginx server to redirect /redirect_me to another page.
# The redirection is configured as a 301 Moved Permanently.
# Includes a custom 404 not found page with Ceci n'est pas une page".


apt-get update
apt-get install -y nginx

mkdir -p /var/nginx/html/
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	add_header X-Served-By $HOSTNAME;
	root /var/www/html;
	index index.html index.htm;

	location /redirect_me {
		return 301 http://cuberule.com/;
	}

	error_page 404 /404.html;
	location /404 {
		root /var/www/html;
		internal;
	}
}" > /etc/nginx/sites-available/default

service nginx restart
