#!/usr/bin/env bash
# Install and configure HAProxy on 1b-01 server
# HAProxy with version == 1.5. to send traffic to web-01 and web-02
# Distribute requests using the roundrobin algorithm
# HAProxy manageable via an init script

apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.0
apt-get update
apt-get install haproxy=2.0.\*

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf $s "global
	log 127.0.0.1 local0 notice
	maxconn 2000
	user haproxy
	group haproxy

defaults
   log     global
   mode    http
   retries 3
   option  redispatch
   timeout connect 3000s
   timeout client  8000s
   timeout server  8000s
   option  httplog
   option  dontlognull

listen myserver
   bind 0.0.0.0:80
   mode http
   stats enable
   stats uri /haproxy?stats
   balance roundrobin
   option httpclose
   option forwardfor
   server 1313-web-01 34.139.21.144 check
   server 1313-web-02 44.192.90.48 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start


