#!/usr/bin/env bash
# configures an Nginx server to listen on port 80.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-available/default
service nginx start
kill "$(pgrep 'nginx' | head -l)"
