#!/usr/bin/env bash
# This script displays a list of currently running processes
# shows all processes, for all users, including those which might not have TTY
# display in a user-oriented format
# Show process hierarchy

ps -auxf
