#!/usr/bin/env bash
# Displays:
# To infinity and beyond indefinitely
# With a sleep 2 in between each iteration
# I am invicible!!! when receiving a SIGTERM signal

while true; do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
