#!/usr/bin/env bash
# This script displays "Best School" 10 times using the while loop
# And displays "Hi" as well on the 9th iteration
a=1
while [ "$a" -le "10" ]
do

	echo "Best School"
	if [ "$a" == 9 ]; then
		echo "Hi"
	fi
	((a++))
done
