#!/usr/bin/env bash
# This script displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the dash is displayed
LIST=$(find "." -name "[!.]*" | sed -e "s/^.*-//")

for i in $LIST; do
	echo "$i"
done

