#!/usr/bin/env bash
# Configures a ufw firwall to block all incoming traffic
#+ except for ports 22, 443 and 80

apt install ufw
ufw default deny incoming
ufw default allow outgoing
ufw allow 22
ufw allow 443
ufw allow 80
ufw enable
